#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/bin/bandix

service_triggers() {
	procd_add_reload_trigger "bandix"
}

reload_service() {
	restart
}

start_service() {
	local enabled
	
	config_load 'bandix'
	config_get_bool enabled 'general' 'enabled' '0'
	
	[ "$enabled" -eq 1 ] || return 1
	
	procd_open_instance bandix
	procd_set_param command $PROG --iface br-lan --mode web
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_set_param pidfile /var/run/bandix.pid
	procd_close_instance
}

# 在OpenWrt中，不需要特殊的stop_service函数
# procd会自动处理服务停止 